In [1]:
import torch

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1], a[1].item(), float(a[1])

(tensor(1.), 1.0, 1.0)

In [4]:
a[2] = 2.0
a


tensor([1., 1., 2.])

In [5]:
torch.tensor([float(a) for a in range(10)])

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [6]:
torch.arange(10).type(torch.DoubleTensor)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [ ]:
points = torch.tensor([[x, y] for x in range(3) for y in range(3)]).type(torch.FloatTensor)
points

In [21]:
points.shape

torch.Size([9, 2])

In [22]:
zp = torch.zeros(points.shape)
zp

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [25]:
points[2,0], points[2,1]

(tensor(0.), tensor(2.))

In [29]:
points[0]

tensor([0., 0.])

In [30]:
points.view(-1, 9)

tensor([[0., 0., 0., 1., 0., 2., 1., 0., 1.],
        [1., 1., 2., 2., 0., 2., 1., 2., 2.]])

In [31]:
points[1:, :]

tensor([[0., 1.],
        [0., 2.],
        [1., 0.],
        [1., 1.],
        [1., 2.],
        [2., 0.],
        [2., 1.],
        [2., 2.]])

In [32]:
points[1:, 0]

tensor([0., 0., 1., 1., 1., 2., 2., 2.])

In [34]:
?torch.unsqueeze

Docstring:
unsqueeze(input, dim) -> Tensor

Returns a new tensor with a dimension of size one inserted at the
specified position.

The returned tensor shares the same underlying data with this tensor.

A :attr:`dim` value within the range ``[-input.dim() - 1, input.dim() + 1)``
can be used. Negative :attr:`dim` will correspond to :meth:`unsqueeze`
applied at :attr:`dim` = ``dim + input.dim() + 1``.

Args:
    input (Tensor): the input tensor.
    dim (int): the index at which to insert the singleton dimension

Example::

    >>> x = torch.tensor([1, 2, 3, 4])
    >>> torch.unsqueeze(x, 0)
    tensor([[ 1,  2,  3,  4]])
    >>> torch.unsqueeze(x, 1)
    tensor([[ 1],
            [ 2],
            [ 3],
            [ 4]])
Type:      builtin_function_or_method


In [41]:
# Understanding squeeze and unsqueeze a tensor
x = torch.tensor([1,2,3,4])
x_u = torch.unsqueeze(x, 1)
x_u

tensor([[1],
        [2],
        [3],
        [4]])

In [61]:
# In[2]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
print(img_t.shape, weights.shape)
img_t, weights

torch.Size([3, 5, 5]) torch.Size([3])


(tensor([[[-0.1090, -0.7284,  0.5796, -0.4119,  0.6711],
          [ 0.7876, -0.5574, -0.0578,  0.6180,  1.1130],
          [-0.2739,  2.2963,  0.1230, -2.1484, -1.0580],
          [-0.4162, -0.3342, -0.7634,  1.8820,  1.4100],
          [ 0.3992,  1.8552,  1.0967, -0.2686, -0.4048]],
 
         [[-0.4378, -0.8048,  0.8616, -1.5140,  1.3408],
          [-0.9288, -0.7073,  1.1574, -0.3663, -0.6444],
          [-0.6761,  1.1012, -1.4716,  1.8130,  1.3793],
          [ 1.5779, -0.1228,  0.8835,  0.5812,  0.7009],
          [-1.5709, -0.2410, -0.1468,  0.7028, -1.2589]],
 
         [[-0.1122, -0.6114, -0.0785,  0.2500,  0.4444],
          [-0.5568, -0.1312,  0.0203,  2.3416, -0.0651],
          [-0.7808,  1.8602,  1.0304, -0.6279, -0.3822],
          [-0.4769, -1.6649, -0.1132,  0.9057,  0.3448],
          [-0.9538, -0.4781, -0.0276,  0.6238, -0.4336]]]),
 tensor([0.2126, 0.7152, 0.0722]))

In [62]:
# In[3]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
print(batch_t.shape)
batch_t

torch.Size([2, 3, 5, 5])


tensor([[[[-2.1418, -1.0305, -0.9609, -0.6876,  1.6747],
          [-0.3175,  1.6457,  0.9897, -0.4149, -0.5998],
          [-0.0976, -1.8780,  0.0468,  1.9805,  0.4391],
          [ 0.9731, -0.6426,  0.7858,  0.4878, -0.2792],
          [-0.9837,  1.3873, -0.9406, -0.4178,  0.0659]],

         [[-0.5803,  0.7585,  0.1412, -1.3239,  0.0895],
          [ 0.0967,  0.1733, -1.2939,  0.0761, -0.3867],
          [ 0.9663, -1.1469,  0.8991, -0.2901, -0.2066],
          [ 0.2643, -0.4219,  0.6456, -1.7823, -0.2775],
          [-0.8489,  0.7288,  1.0670, -0.7340,  0.5099]],

         [[ 1.0408,  0.9069, -3.3066, -0.1595,  0.8415],
          [ 0.3209, -0.0641,  0.3792, -1.5061, -0.8055],
          [-1.2001, -1.0738, -1.1097,  0.3130, -0.8721],
          [ 0.6300, -0.2924,  0.3002, -0.8188, -1.3120],
          [-0.4202, -0.4668,  0.8105, -0.3109,  0.4952]]],


        [[[-0.4297,  0.0511,  1.7481,  1.5133, -0.0131],
          [ 0.2749,  0.2281, -0.0379,  0.1618,  0.6127],
          [ 1.1308,  0.

In [63]:
# In[4]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
print(img_gray_naive.shape, batch_gray_naive.shape)
img_gray_naive


torch.Size([5, 5]) torch.Size([2, 5, 5])


tensor([[-0.2197, -0.7148,  0.4542, -0.5586,  0.8188],
        [-0.2326, -0.4653,  0.3733,  0.8644,  0.1345],
        [-0.5769,  1.7526, -0.1061, -0.3211, -0.0203],
        [ 0.2282, -0.7073,  0.0023,  1.1230,  0.8186],
        [-0.7085,  0.3787,  0.3074,  0.3527, -0.6991]])

In [56]:
# In[5]:
# 
# PyTorch will allow us to multiply things that are the same shape, as well as shapes where one operand is of size 1 in a given dimension. 
# It also appends leading dimensions of size 1 automatically. This is a feature called broadcasting. 
# batch_t of shape (2, 3, 5, 5) is multiplied by unsqueezed_weights of shape (3, 1, 1), resulting in a tensor of shape (2, 3, 5, 5), 
# from which we can then sum the third dimension from the end (the three channels):
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape


(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [81]:

img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [76]:
# 

weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named
                         

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [80]:

img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)


img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [79]:

weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names


(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [78]:

gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names


(torch.Size([5, 5]), ('rows', 'columns'))

In [82]:
gray_named = (img_named[..., :3] * weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [83]:
# In[12]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names


(torch.Size([5, 5]), (None, None))

In [88]:

# Managing a tensor's dtype attribute

double_points = torch.ones(10,2, dtype=torch.double)
short_points = torch.tensor([[1,2], [3,4]], dtype=torch.short)
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [91]:

double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
double_points = torch.zeros(10, 2).to(torch.float32)
short_points = torch.ones(10, 2).to(dtype=torch.int)
double_points.dtype, short_points.dtype

(torch.float32, torch.int32)